### ISSUE TITLE
Bad Download when video title contains colon : on Windows

### ISSUE THREAD

**Issue by Zulu-Inuoe** [barbarbar338/ytdownload#1]
On Windows, via the CLI, I tried downloading the video titled `TwoSet Violin & SSO: Mendelssohn Violin Concerto` as follows:

`ytdownload https://www.youtube.com/watch?v=zlRRdGnzA00`

this started and completed the download successfully:

```
[YTDownload] Downloading 100.000%
╔══════════════════════════════════════════════════╤═══════════════════╤═════════╗
║ YTDownload                                       │ Status            │ Percent ║
╟──────────────────────────────────────────────────┼───────────────────┼─────────╢
║ TwoSet Violin & SSO: Mendelssohn Violin Concerto │ Download Finished │ 100%    ║
╚══════════════════════════════════════════════════╧═══════════════════╧═════════╝

Downloaded in: 24.000s
Downloaded to ./videos/TwoSet Violin & SSO: Mendelssohn Violin Concerto.mp4
```

But when I looked in the `videos` directory, there was a 0 byte **file** in there titled `TwoSet Violin & SSO`

So I'm guessing there's an issue when the video title contains colons, which are not allowed (besides for drive letters) on Windows.

**Comment by barbarbar338** [comment]
Thanks for the report, fixed with `ytdownload@2.1.1` <3
